# Script to setup existing keystore file
# This will move the keystore to correct location and create keystore.properties

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Setting Up Existing Keystore" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

$rootKeystore = Join-Path $PSScriptRoot "..\my-release-key.keystore"
$targetKeystore = Join-Path $PSScriptRoot "app\release.keystore"
$targetDir = Join-Path $PSScriptRoot "app"

# Check if keystore exists in root
if (-not (Test-Path $rootKeystore)) {
    Write-Host "✗ ERROR: my-release-key.keystore not found in app folder" -ForegroundColor Red
    Write-Host "  Expected location: $rootKeystore" -ForegroundColor Yellow
    exit 1
}

Write-Host "Found keystore at: $rootKeystore" -ForegroundColor Green
Write-Host ""

# Create app directory if it doesn't exist
if (-not (Test-Path $targetDir)) {
    New-Item -ItemType Directory -Path $targetDir -Force | Out-Null
}

# Copy keystore to correct location
Write-Host "Copying keystore to: $targetKeystore" -ForegroundColor Yellow
Copy-Item $rootKeystore -Destination $targetKeystore -Force

if (Test-Path $targetKeystore) {
    Write-Host "✓ Keystore copied successfully" -ForegroundColor Green
} else {
    Write-Host "✗ ERROR: Failed to copy keystore" -ForegroundColor Red
    exit 1
}

Write-Host ""

# Create keystore.properties file
$keystorePropsPath = Join-Path $targetDir "keystore.properties"
$keystorePassword = "123456"
$keyAlias = "my-key-alias"

Write-Host "Creating keystore.properties file..." -ForegroundColor Yellow

$propsContent = @"
# Android Release Keystore Configuration
# IMPORTANT: Keep this file secure and do NOT commit it to version control
# This file is automatically generated

MYAPP_RELEASE_STORE_FILE=release.keystore
MYAPP_RELEASE_KEY_ALIAS=$keyAlias
MYAPP_RELEASE_STORE_PASSWORD=$keystorePassword
MYAPP_RELEASE_KEY_PASSWORD=$keystorePassword
"@

$propsContent | Out-File -FilePath $keystorePropsPath -Encoding UTF8

if (Test-Path $keystorePropsPath) {
    Write-Host "✓ keystore.properties created successfully" -ForegroundColor Green
} else {
    Write-Host "✗ ERROR: Failed to create keystore.properties" -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host "  ✓ SETUP COMPLETE!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""
Write-Host "Keystore Details:" -ForegroundColor Cyan
Write-Host "  Location: $targetKeystore" -ForegroundColor White
Write-Host "  Alias: $keyAlias" -ForegroundColor White
Write-Host "  Password: 123456" -ForegroundColor White
Write-Host ""
Write-Host "Configuration:" -ForegroundColor Cyan
Write-Host "  Properties: $keystorePropsPath" -ForegroundColor White
Write-Host ""
Write-Host "Next step: Build your AAB file" -ForegroundColor Cyan
Write-Host "  Run: .\build-release-aab.ps1" -ForegroundColor White
Write-Host "  Or: .\build-release-aab.bat" -ForegroundColor White
Write-Host ""
