@echo off
REM Script to setup existing keystore file
REM This will copy the keystore to correct location and create keystore.properties

echo ========================================
echo   Setting Up Existing Keystore
echo ========================================
echo.

cd /d "%~dp0"

REM Check if keystore exists in root app folder
if not exist "..\my-release-key.keystore" (
    echo ERROR: my-release-key.keystore not found in app folder
    echo   Expected location: ..\my-release-key.keystore
    pause
    exit /b 1
)

echo Found keystore in app folder
echo.

REM Create app directory if it doesn't exist
if not exist "app" mkdir app

REM Copy keystore to correct location
echo Copying keystore to app\release.keystore...
copy /Y "..\my-release-key.keystore" "app\release.keystore" >nul

if exist "app\release.keystore" (
    echo Keystore copied successfully
) else (
    echo ERROR: Failed to copy keystore
    pause
    exit /b 1
)

echo.

REM Create keystore.properties file
echo Creating keystore.properties file...

(
    echo # Android Release Keystore Configuration
    echo # IMPORTANT: Keep this file secure and do NOT commit it to version control
    echo # This file is automatically generated
    echo.
    echo MYAPP_RELEASE_STORE_FILE=release.keystore
    echo MYAPP_RELEASE_KEY_ALIAS=my-key-alias
    echo MYAPP_RELEASE_STORE_PASSWORD=123456
    echo MYAPP_RELEASE_KEY_PASSWORD=123456
) > app\keystore.properties

if exist "app\keystore.properties" (
    echo keystore.properties created successfully
) else (
    echo ERROR: Failed to create keystore.properties
    pause
    exit /b 1
)

echo.
echo ========================================
echo   SETUP COMPLETE!
echo ========================================
echo.
echo Keystore Details:
echo   Location: %CD%\app\release.keystore
echo   Alias: my-key-alias
echo   Password: 123456
echo.
echo Next step: Build your AAB file
echo   Run: build-release-aab.bat
echo.

pause
